import type { Metadata } from "next";
/* import {Montserrat as Font_Montserrat} from "next/font/google"; */
import "./globals.css";

import Header from "@/components/Header";
import PromoBanner from "@/components/PromoBanner";

/* const Montserrat = Font_Montserrat({
  weight: ['300','400','500','600','700', '800', '900'],
  subsets: ['latin'],
  variable: '--font-barlow',
  display: 'swap'
}) */

export const metadata: Metadata = {
  title: "Shop.co",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <PromoBanner/>
        <Header/>
        {children}
      </body>
    </html>
  );
}
